workdir:
  /path/to/dir
dataset_chacteristics:
  /path/to/dir/dataset_characteristics.tsv
mapping_file:
  /path/to/dir/names_focal_map.tsv
min_taxa: 200
max_taxa: 400
cd_hit_perc_id: 0.8
focal_taxonomy: phylum_of_interest
clusters: [protein_file_id_1, protein_file_id_2, protein_file_id_3]
